name: React-Advanced test push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI: false
    steps:
      - name: Print name
        run: echo "test push request"
      - name: print project name
        run: echo "react"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: Build project
        run: npm run build